using Administration = QadeerApp.Administration.Pages;

[assembly: NavigationMenu(9000, "Administration", icon: "fa-wrench")]
[assembly: NavigationLink(9100, "Administration/Languages", typeof(Administration.LanguagePage), icon: "fa-comments")]
[assembly: NavigationLink(9200, "Administration/Translations", typeof(Administration.TranslationPage), icon: "fa-comment-o")]
[assembly: NavigationLink(9250, "Administration/Departments", typeof(Administration.DepartmentPage), icon: "fa-sitemap")]
[assembly: NavigationLink(9260, "Administration/Specializations", typeof(Administration.SpecializationPage), icon: "fa-tags")]
[assembly: NavigationLink(9270, "Administration/Training Terms", typeof(Administration.TrainingTermPage), icon: "fa-graduation-cap")]
[assembly: NavigationLink(9275, "Administration/Training Courses", typeof(Administration.TrainingCoursePage), icon: "fa-book")]
[assembly: NavigationLink(9280, "Administration/Training Grades", typeof(Administration.TrainingGradePage), icon: "fa-upload")]
[assembly: NavigationLink(9285, "Administration/Training Grades Pivot", typeof(Administration.TrainingGradePivotPage), icon: "fa-table")]
[assembly: NavigationLink(9286, "Administration/Denied & Withdrawn Statistics", typeof(Administration.TrainingGradePivotDeniedPage), icon: "fa-table")]
[assembly: NavigationLink(9290, "Administration/Training Calendars", typeof(Administration.TrainingCalendarPage), icon: "fa-calendar")]
[assembly: NavigationLink(9291, "Administration/Training Calendar Breaks", typeof(Administration.TrainingCalendarBreakPage), icon: "fa-plane")]
[assembly: NavigationLink(9292, "Administration/Training Calendar Notes", typeof(Administration.TrainingCalendarNotePage), icon: "fa-sticky-note")]
[assembly: NavigationLink(9293, "Administration/Portal Links", typeof(Administration.PortalLinkPage), icon: "fa-link")]
[assembly: NavigationLink(9294, "Administration/Training Schedule Imports", typeof(Administration.TrainingScheduleImportPage), icon: "fa-table")]
[assembly: NavigationLink(9295, "Administration/Training Course Files", typeof(Administration.TrainingCourseFilePage), icon: "fa-file-text")]
[assembly: NavigationLink(9296, "Administration/Course Coordinators", typeof(Administration.TrainingCourseCoordinatorPage), icon: "fa-user-circle")]
[assembly: NavigationLink(9300, "Administration/Roles", typeof(Administration.RolePage), icon: "fa-lock")]
[assembly: NavigationLink(9400, "Administration/User Management", typeof(Administration.UserPage), icon: "fa-users")]
